Tattoo Art Bar & Readings
A0
A2
A3
A4
A5
A6
A7
A8
A9…(etc)…Z9

￼

￼

Tattoo 
Referencing: https://tattooing101.com/learn/styles/

Generative Art 

Traditional / Old School Tattoo Style
Neo Traditional✨
New School✨
Black and Grey ✨
Realism ✨
Japanese ✨
Script / Lettering 
Watercolour 
Geometric
Embroidery
Portraits  
Pet and Animal
Colour
Back&white
Cosmetic
Prison
Mandala
Minimalist
Graffiti Art
Surrealism
Sketch
Blackwork ✨
Trash Polka
Dotwork✨
Negative Space
Fine Art✨
Micro Tattoos✨
3-D
Cartoon/Anime Tattoos✨
Chicano
Bio-mechanical
Hyperrealism ✨
Religious + Symbolic + Tribal + Spiritual + Demonic✨
Horror
Continuous line✨
Illustrative✨
Abstract✨


#DAO #Digital-Contract

https://youtube.com/@Coffeezilla		***Reference Source Tool***

(Decentralized Autonomous Organization)
Vote Projects 

Money from people being late to join
￼
#Projects 
￼
Crypto Token✨

￼
Sensory Research Media Lab + NFT 
https://youtu.be/_VC2RdSWZc8
￼

https://broomx.com/devices/mkpro

￼

#Projects
Utility token the future of large group activities, event management, event coordination, 
event participation
Creator, creative focus 

The death of social media being eminent. Reality television with a web three Inc. infrastructure for voting purposes, as well as matchmaking and quality of life fulfillment.

Universal allowance plus lenient drug use, streamer singularity, paid participation, dopamine overdose, natural through the use of external devices. 

VR-100% virtual 
Augmented Reality=<99% Virtual
Mixed Reality=<99%  Virtual 

Minimum 1% Virtual 
￼

￼

NFT Creation Guide
￼
New Security/Setup checklist
 
Run network scanner to map existing devices
Strong WiFi password
Strong modem/AP management U & P
Change default router IP
WIFI is WPA2/AES
Checked windows clients for malware
Updated network device firmwares
Disable WPS if not in use
No DMZS are active
Router remote management disabled
Change default SSID
Setup guest network
Windows clients are up to date
Bluetooth devices not broadcasting sensitive Info 
Client infomed about 2FA for smart device accounts
Limit DHCP range based on client needs
Using 5GHz WiFi Where Possible
Access point location optimal
WIFI extenders in use where needed
Router port forwarding disabled where possible 
WIFI access points/routers using least congested CH
Port 32764 is closed
Run port scan on external IP
Ensured all devices are connected to WIFI
Customer left with apropriate documentation
 
Total tasks 25
Completed tasks 25

% of Completed tasks
is everything good to go? Yep! 

￼
Types of NFT’s
-picture 
    •collection generated by algorithm
    •collection generated by algorithm + curated 
-animated picture
-song
-song + picture
-song + animated picture 
Levels of complexity in NFT’s 
-Mutable when traded.     
-attached to blockchain Recreatable and immutable
(DeafBeef entropy collection degrades and becomes fragmented with artifacts and distortion)
(Attributes can be anything ranging from colour shape design or sound of the nft)
-Mutable attributes depending on input
     •interactive (Push button animations)
     •Triggered when 2 or more in 1 collection 
-Mutable attributes depending on specific source
     •blockchain gas fees
     •season
-Special trading restrictions
     •can only be traded on specific days like full moons***
     •can only be traded at specific times of the day afternoon 11:11am to 1:11pm 

Below are a few categories of Solana projects we’re interested in funding. You can also see a running list of specific project ideas
Censorship Resistance
DAO Tooling
Developer Tooling
Education☑️
Payments / Solana Pay
Financial Inclusion
Climate Change
Academic Research☑️

Blockchain Technology Framework
PRIVATE -Ripple- hyper ledger-corda
CONSORTIUM/ FEDERATED-r3-EWF-B3i-Libra
PERMISSIONED-
PERMISSIONLESS-BTC-ETH
PUBLIC



￼

#Projects

#Emoji-Project 
Client optional Picture
Version 1 series 1 Covid edition 

Emoji series
-(Phase1)
I made an emoji collage for my favourite streamers Content creators

🎦 = B role Timelapse footage
	Google search desktop
	Download
	Collaging
	Printable Poster
	Shopify Poster Store Launch (phase1)

Collect fan art picture☑️
Record emoji collage Creation🔘
Edit video into 1-3 minute TikTok🔘
Make YouTube Thumbnail🔘

SssniperWolf✅🎦 Doja Cat✅ 39Daph✅
Aloona ✅
Pokimane✅🎦
LillyPichu ✅
QuarterJade✅
Sydeon ✅
Yvonnie✅
Aria ✅
Emiru Aug 7th 1 million followers ✅
Sykkuno
Valkyrae ✅
xQc
Fuslie ✅
HaChubby ✅
QTcinderella
Ludwig
Mizkif 
Alinity
Amouranth
JustaMinx
CodeMiko
Sweet Anita 
KyootBot
Kiera Pleaze🎦
SodaPoppin
Sydsnap

-(Phase2)
I made trading cards out of my favourite streamers
	health = current stream sub
	attack = view count/videos/interactions
	Special Effect = Top rated meme/CatchPhrase

-(Phase3)
conduct research on participants for interest in NFT ownership
Bitcoin/NFT receipts Machine ATM/Camera Booth 

-(Phase4)
MeshLab
augmented reality filter option

-(Phase5)
Blender 3D emoji background 
Blender 3D scripting NFT
Migraine Art research / BCI EEG /
Ai Generated Art {dynamic}
Biometric Generated Art

￼


#Projects
